import Navbar from '@/components/sections/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/sections/Footer'
import ReduxProvider from '@/components/utilities/ReduxProvider'
import {ClerkProvider, auth} from "@clerk/nextjs"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { userId } = auth();
  return (
    <ClerkProvider>
    <ReduxProvider>
    <html lang="en">
      <body className={inter.className}>
      <Navbar userId={userId as string} />
        {children}
        <Footer></Footer>
        </body>
    </html>
    </ReduxProvider>
    </ClerkProvider>
  )
}
