import './globals.css'
import { Inter } from 'next/font/google'
import Header from './modules/header';
import Footer from './modules/footer';
import ReduxProvider from '@/components/utilits/ReduxProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxProvider>
    <html lang="en">
      <body className={inter.className}>
        
      <Header></Header>
      <main className='md:pl-16 md:pr-16 pl-4 pr-4 z-10'>
        {children}
        </main>
        <Footer></Footer>
        
        </body>
    </html>
    </ReduxProvider>
  )
}
